都度起動バッチをNablarchバッチの内容に修正
Fintan-contents/application-architecture-sample pull request #8
Opened 2022-07-25 06:58 UTC by opengl-8080

基本はword版を持ってきつつ、内容で気になったところは適宜修正しています。

## 内容が気になったので書き直した部分
- 4.1.2.2. 強制停止
  - プロセス停止制御ハンドラは[都度起動バッチのハンドラ最小構成](https://nablarch.github.io/docs/LATEST/doc/application_framework/application_framework/batch/nablarch_batch/architecture.html#id5)に含まれていなかったので、ハンドラを追加することで対応することを明記する形にしました
  - 元の文章だと、何もしなくてもNablarch標準の組み込み機能で勝手にやってくれそうに読めると思えたので
- 4.1.3. 基本的な処理シーケンス
  - 「業務コンポーネントの基本処理シーケンス」に関する記述を削っています
  - 参照先の記述は、Excel版の方（全体概要）には無いためです
  - シーケンス図上のコメントからも削っています
- 4.1.5.2. 入力ファイルの行データが0件の場合
  - 「1レコード目が”NO DATA”の場合」を削りました
  - 方式設計書なのに、個別のファイルフォーマットの内容に踏み込みすぎているように思えたので、削りました
  - 強いて方式設計書で触れるなら、「ファイルごとに定められたデータ無しであることを表す形式の場合は～」くらいに留めて、「具体的な形式は個別のインタフェース定義書参照」となると思いました
  - ただ、そこまで書くのもややこしいと思えたので、単に行データ0件の場合だけにしました
- 4.1.6.2. 入力データがファイルの場合
  - こちらも、元の文章だと何もしなくてもNablarch標準機能でやってくれそうな書き方になっていたので、 `ResumeDataReader` を使うことで対応するということを明記する形にしました

## シーケンス図に関して
Excel の図形で再現するのは大変そうに思えたので、 PlantUML で書いたものを貼り付けてます。
一応、ソースファイルを `uml/nablarch_sample/都度起動バッチ.pu` に置いてます。

2022-07-26 01:24 UTC, kumagoro1202 requested changes
4.1.2.2.強制停止
> プロセス停止制御ハンドラはデータベースに保存された処理停止フラグをループごとに監視しており、
> フラグがオンになるとバッチを強制停止させる。

という記述に小さな違和感を覚えました。ループごとに監視するのはループ制御してるハンドラの後続に入れるからなので、プロセス停止制御ハンドラがループごとに監視しているという書き方に違和感があります。
恐らくプロセス停止ハンドラの解説書に

>本ハンドラは、以下のようなループ制御を行なうハンドラの後続に配置することで、 ループを中断してプロセス停止要求を示す例外を送出する機能を提供する。

とあるのでループ制御を行うハンドラの後続に置くことは前提として書いてくれたのかなと思うんですが、一応方式設計書上でも触れておいたほうがいいのかなと思いました。

> プロセス停止制御ハンドラはデータベースに保存された処理停止フラグを監視しており、
> フラグがオンになるとバッチを強制停止させる。
> トランザクションループ制御ハンドラの後続に配置することで、ループごとに処理停止フラグを監視させることができる。
> したがって、処理停止フラグをオンにするジョブ（都度起動バッチ停止ジョブ）を用意することで、
> 処理対象の入力リクエストがあってもループ処理を抜けてバッチを強制停止させられるようになる。

とかがいいかなと思いますがどうでしょう。

2022-07-26 01:35 UTC, kumagoro1202 commented
> 4.1.6.2. 入力データがファイルの場合
> こちらも、元の文章だと何もしなくてもNablarch標準機能でやってくれそうな書き方になっていたので、ResumeDataReader を使うことで対応するということを明記する形にしました

ResumeDataReaderには触れなくて元の記述でいいかなと思いました。
ファイルが入力の場合は[FileBatchAction (ファイル入力のバッチアクションのテンプレートクラス)](https://nablarch.github.io/docs/LATEST/javadoc/nablarch/fw/action/FileBatchAction.html)を継承して業務Actionを実装するのが通常で、その場合意識しなくてもResumeDataReaderが使われるのでNablarch標準機能でやっていると言ってもいいのかなと思いました。

2022-07-26 01:43 UTC, kumagoro1202 commented
> 4.1.7.1.	エラー発生時の処理
> ※本システム共通となるエラー発生時の処理は、【2.5.2. エラー発生時の共通方針】を参照。

2.5.エラー処理概要 のセクションは常駐バッチの対応時に作成予定ですか？

2022-07-27 05:25 UTC, opengl-8080 commented
> > 4.1.7.1.	エラー発生時の処理
> > ※本システム共通となるエラー発生時の処理は、【2.5.2. エラー発生時の共通方針】を参照。
> 
> 2.5.エラー処理概要 のセクションは常駐バッチの対応時に作成予定ですか？

YES です。

2022-07-27 05:26 UTC, opengl-8080 commented
https://github.com/Fintan-contents/application-architecture-sample/pull/8/commits/16d300f79d010c2fcc42a436fe2c9c1fa9ab246c

ちょっとだけ文章修正して取り込みました。

> 4.1.2.2.強制停止
> 
> > プロセス停止制御ハンドラはデータベースに保存された処理停止フラグをループごとに監視しており、
> > フラグがオンになるとバッチを強制停止させる。
> 
> という記述に小さな違和感を覚えました。ループごとに監視するのはループ制御してるハンドラの後続に入れるからなので、プロセス停止制御ハンドラがループごとに監視しているという書き方に違和感があります。 恐らくプロセス停止ハンドラの解説書に
> 
> > 本ハンドラは、以下のようなループ制御を行なうハンドラの後続に配置することで、 ループを中断してプロセス停止要求を示す例外を送出する機能を提供する。
> 
> とあるのでループ制御を行うハンドラの後続に置くことは前提として書いてくれたのかなと思うんですが、一応方式設計書上でも触れておいたほうがいいのかなと思いました。
> 
> > プロセス停止制御ハンドラはデータベースに保存された処理停止フラグを監視しており、
> > フラグがオンになるとバッチを強制停止させる。
> > トランザクションループ制御ハンドラの後続に配置することで、ループごとに処理停止フラグを監視させることができる。
> > したがって、処理停止フラグをオンにするジョブ（都度起動バッチ停止ジョブ）を用意することで、
> > 処理対象の入力リクエストがあってもループ処理を抜けてバッチを強制停止させられるようになる。
> 
> とかがいいかなと思いますがどうでしょう。

2022-07-27 07:04 UTC, kumagoro1202 approved these changes

2022-07-27 07:04 UTC, merged